# Generated by Django 5.2.18 on 2026-10-08 10:53

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='taxonomy_skill_name_trgm', opclasses=['gin_trgm_ops'])],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='taxonomy_skill_name_ci_unique')],
            },
        ),
    ]
