# Generated by Django 5.2.18 on 2026-10-08 10:53

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_extensions'),
        ('taxonomy', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=80)),
                ('headline', models.CharField(blank=True, max_length=140)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('work_mode_preference', models.CharField(blank=True, choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'On-site')], max_length=8)),
                ('experience_level', models.CharField(blank=True, choices=[('INTERN', 'Intern'), ('ENTRY', 'Entry'), ('MID', 'Mid'), ('SENIOR', 'Senior'), ('LEAD', 'Lead')], max_length=8)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections only'), ('COMMUNITY', 'Community members'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=12)),
                ('show_contact', models.BooleanField(default=False)),
                ('show_history', models.BooleanField(default=True)),
                ('accepts_referral_requests', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['display_name'], name='users_profile_name_trgm', opclasses=['gin_trgm_ops']), models.Index(fields=['country_code', 'city'], name='users_profile_location')],
                'constraints': [models.CheckConstraint(condition=models.Q(('visibility__in', ['PUBLIC', 'CONNECTIONS', 'COMMUNITY', 'PRIVATE'])), name='users_userprofile_visibility_valid'), models.CheckConstraint(condition=models.Q(('work_mode_preference__in', ['', 'REMOTE', 'HYBRID', 'ONSITE'])), name='users_userprofile_work_mode_valid'), models.CheckConstraint(condition=models.Q(('experience_level__in', ['', 'INTERN', 'ENTRY', 'MID', 'SENIOR', 'LEAD'])), name='users_userprofile_experience_level_valid'), models.CheckConstraint(condition=models.Q(('country_code', django.db.models.functions.text.Upper('country_code'))), name='users_userprofile_country_code_uppercase')],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('family', models.UUIDField(default=uuid.uuid4)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['family'], name='users_refresh_family'), models.Index(fields=['user', 'revoked_at'], name='users_refresh_user'), models.Index(fields=['expires_at'], name='users_refresh_expires')],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='users_userblock_unique'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='users_userblock_not_self')],
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=160)),
                ('degree', models.CharField(blank=True, max_length=120)),
                ('field_of_study', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='users_usereducation_dates_ordered')],
            },
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('organization_name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='users_userexperience_dates_ordered')],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('HAS', 'Has'), ('INTERESTED', 'Interested in')], max_length=10)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='taxonomy.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'skill'), name='users_userskill_unique'), models.CheckConstraint(condition=models.Q(('kind__in', ['HAS', 'INTERESTED'])), name='users_userskill_kind_valid')],
            },
        ),
    ]
