# Generated by Django 5.2.18 on 2026-10-06 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System')], max_length=8)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.UUIDField()),
                ('organization_id', models.UUIDField(blank=True, null=True)),
                ('community_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id', 'created_at'], name='audit_audit_target__a22730_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['organization_id', 'created_at'], name='audit_audit_organiz_01c53f_idx'), models.Index(fields=['community_id', 'created_at'], name='audit_audit_communi_4822a7_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_type__in', ['USER', 'SYSTEM'])), name='audit_auditlog_actor_type_valid')],
            },
        ),
    ]
